site3/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('', views.index, name='index'),
]

site3/pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:world_id>', views.detail, name='detail'),
    path('reserv/<int:world_id>', views.reservation, name='reservation'),
    path('question/', views.index1, name='index1'),
    path('notification/', views.notification, name='notification'),
    path('QnA/', views.QnA, name='QnA'),    
    path('question/<int:question_id>', views.detail1, name='detail1'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
]

site3/pybo/models.py
from unittest.util import _MAX_LENGTH
from django.db import models

# Create your models here.

class world(models.Model):
    CONTINENT = models.CharField(max_length=100)
    COUNTRY = models.CharField(max_length=100)
    p1 = models.CharField(max_length=50, null=True)
    p2 = models.CharField(max_length=50, null=True)
    p3 = models.CharField(max_length=50, null=True)
    p4 = models.CharField(max_length=50, null=True)
    p5 = models.CharField(max_length=50, null=True)
    p6 = models.CharField(max_length=50, null=True)
    p7 = models.CharField(max_length=50, null=True)
    p8 = models.CharField(max_length=50, null=True)

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    
    def __str__(self):
        return self.subject
    
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

site3/pybo/forms.py
from django import forms
from pybo.models import world
from pybo.models import Question, Answer

class worldForm(forms.ModelForm):
    class Meta:
        model = world
        fields = ['CONTINENT', 'COUNTRY', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8']
        labels = {
            'CONTINENT' : '대륙',
            'COUNTRY' : '나라이름',
            'p1' : 'p1',
            'p2' : 'p2',
            'p3' : 'p3',
            'p4' : 'p4',
            'p5' : 'p5',
            'p6' : 'p6',
            'p7' : 'p7',
            'p8' : 'p8',
        }

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성
        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }
        labels = {
            'subject': '제목',
            'content': '내용',
        }  

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

site3/pybo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import world
from django.shortcuts import render
from .models import Question
from .forms import QuestionForm, AnswerForm
from django.http import HttpResponseNotAllowed


# 메인 페이지
def index(request):
    worlds = world.objects
    return render(request, 'pybo/main_page.html', {'worlds': worlds} )

def detail(request, world_id):
    wi = world.objects.get(id=world_id)
    p1 = world.objects.get(id=world_id)
    p2 = world.objects.get(id=world_id)
    p3 = world.objects.get(id=world_id)
    p4 = world.objects.get(id=world_id)
    p5 = world.objects.get(id=world_id)
    p6 = world.objects.get(id=world_id)
    p7 = world.objects.get(id=world_id)
    p8 = world.objects.get(id=world_id)
    context = {'wi': wi, 'p1': p1, 'p2': p2, 'p3': p3, 'p4': p4, 'p5': p5, 'p6': p6, 'p7': p7, 'p8': p8}
    return render(request, 'pybo/reserv_form.html', context)

def reservation(request, world_id):
    worlds = world.objects
    context = {'worlds': worlds}
    return render(request, 'pybo/main_page.html', context)

def index1(request):
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list': question_list}
    return render(request, 'pybo/question_list.html', context)

def detail1(request, question_id):
    question = Question.objects.get(id=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

def answer_create(request, question_id):
    """
    pybo 답변등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail1', question_id=question.id)
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)
    
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index1')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

def notification(request):
    context = {}
    return render(request, 'pybo/notification.html', context)

def QnA(request):
    context = {}
    return render(request, 'pybo/QnA.html', context)

site3/templates/FAQ.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <title>FAQ</title>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'pybo:index' %}">Main</a>
      <button class="navbar-toggler" type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                  <a class="nav-link" href="#"></a>
              </li>
          </ul>
      </div>
  </div>
</nav>
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

site3/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>여행하는 오리</title>
    <style>
        @font-face {
            font-family: 'S-CoreDream-3Light';
            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_six@1.2/S-CoreDream-3Light.woff') format('woff');
            font-weight: normal;
            font-style: normal;
        }

        * {
            font-family: 'S-CoreDream-3Light';
            color: #333;
        }
        #wrap {
            margin: 0 auto;
            width: 100%;
        }
        .nav {
            width:80%;
            margin: 0 auto;
            height: 7vh;
        }
        .nav.navbar {
            --bs-navbar-padding-y: 1.5rem !important;
        }
        #container {
            width: 80%;
            margin: 0 auto;
        }
        #vimg {
            width:100%;
            object-fit: cover;
            margin: 0 auto;
            padding:3vh 0;
        }
        #vimg img {
            display:block;
            width:100%;
            height:60%;
            object-fit: contain;
            object-position: center;
            margin: auto auto;
        }
        /* #area {
            width:80%;
            margin-bottom:20px;
        } */
        #select {
            margin:0 auto;
            margin-bottom: 20px;
        }
        #lot {
            width:100%;
            margin: 0 auto;
            border: 2px solid #dfdfdf;
            margin-bottom: 7vh;
            box-sizing: none;
        }
        #lot #table0 {
            width:100%;
            height:100%;
            background:url(../../static/parking-lot.jpg);
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center;
        }
        #lot #table0 a {
            text-decoration: none;
            font-size:2px;
            color:rgba(2,2,2,0.1)
        }
        #lot .line {
            margin: 0 auto;
            padding:10px;
        }
        #lot .line button {
            display: inline-block;
            width:9%;
            margin-left:0.5%;
            margin-bottom:10px;
            padding: 10px;
        }
        #lot .line .text {
            color: #555;
            text-align: right;
            margin-top:30px;
            margin-right:10px;
            font-size: 18px;
            font-weight:700;
        }
        #lot .line .text span {
            font-size:1.3em;
            font-weight: 900;
            color: #c9df00;
        }
        /* #lot .line:last-child {
            margin-bottom: 0;
        }
        #lot .line .p-area {
            width: 9%;
            height: 100%;
            border: 1px solid #d8d8d8;
            float: left;
            margin-right: 1%;
        }
        #lot .line .p-area:last-child {
            margin-right: 0;
        } */
        #footer {
            height: 20vh;
            background-color: #333
        }
        #footer .fbox {
            width: 80%;
            margin: 0 auto;
            padding-top: 7vh;
        }
        #footer .fbox a.glow-on-hover {
            width: 450px;
            height: 80px;
            border: none;
            outline: none;
            color: #fff;
            background: #111;
            cursor: pointer;
            position: relative;
            z-index: 0;
            border-radius: 10px;
            margin: 0 auto;
            display:block;
            text-decoration: none;
            text-align: center;
        }
        
        #footer .fbox a.glow-on-hover:before {
            content: '';
            background: linear-gradient(45deg, #ff0000, #ff7300, #fffb00, #48ff00, #00ffd5, #002bff, #7a00ff, #ff00c8, #ff0000);
            position: absolute;
            top: -2px;
            left:-2px;
            background-size: 400%;
            z-index: -1;
            filter: blur(5px);
            width: calc(100% + 4px);
            height: calc(100% + 4px);
            animation: glowing 20s linear infinite;
            opacity: 0;
            transition: opacity .3s ease-in-out;
            border-radius: 10px;
        }
        
        #footer .fbox a.glow-on-hover:active {
            color: #000
        }
        
        #footer .fbox a.glow-on-hover:active:after {
            background: transparent;
        }
        
        #footer .fbox a.glow-on-hover:hover:before {
            opacity: 1;
        }
        
        #footer .fbox a.glow-on-hover:after {
            z-index: -1;
            content: '';
            position: absolute;
            width: 100%;
            height: 100%;
            background: #111;
            left: 0;
            top: 0;
            border-radius: 10px;
        }
        
        @keyframes glowing {
            0% { background-position: 0 0; }
            50% { background-position: 400% 0; }
            100% { background-position: 0 0; }
        }

        #footer .fbox a.glow-on-hover span {
            display: block;
            color: #fff;
            font-weight:700;
            font-size: 1.8em;
            padding-top:21px;
        }
        #footer .fbox a.glow-on-hover:hover span {
            color:#c9df00;
            transition-duration: 3s;
        }
        .clr::after {
            content: "";
            display: block;
            clear: both;
        }
    </style>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!--J Query-->
<script src="{% static 'jquery-3.6.1.min.js' %}"></script>
</body>
</html>

site3/templates/navbar.html
<nav class="nav navbar navbar-expand-lg navbar-light bg-white border-bottom">
    <div class="hdbox container-fluid">
        <a id="logo" href="{% url 'pybo:index' %}"></a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</nav>

site3/templates/pybo/QnA.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif;}
.w3-sidebar {
  z-index: 3;
  width: 250px;
  top: 43px;
  bottom: 0;
  height: inherit;
}
</style>
</head>
<body>

<!-- Navbar -->
<div class="w3-top">
    <div class="w3-bar w3-theme w3-top w3-left-align w3-large">
      <a class="w3-bar-item w3-button w3-right w3-hide-large w3-hover-white w3-large w3-theme-l1" href="javascript:void(0)" onclick="w3_open()"><i class="fa fa-bars"></i></a>
      <a href="#" class="w3-bar-item w3-button w3-theme-l1">여행하는오리</a>
    </div>
  </div>
  
  <!-- Sidebar -->
  <nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
    <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
      <i class="fa fa-remove"></i>
    </a>
    <h4 class="w3-bar-item"><b>Menu</b></h4>
    <a class="w3-bar-item w3-button w3-hover-black" href="../../../pybo/">메인</a>
    <a class="w3-bar-item w3-button w3-hover-black" href="../../../pybo/notification">공지사항</a>
    <a class="w3-bar-item w3-button w3-hover-black" href="../../../pybo/question">FAQ</a>
    <a class="w3-bar-item w3-button w3-hover-black" href="../../../pybo/QnA">QnA</a>
  </nav>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- Main content: shift it to the right by 250 pixels when the sidebar is visible -->
<div class="w3-main" style="margin-left:250px">

  <div class="w3-row w3-padding-64">
    <div class="w3-twothird w3-container">
      <h1>서비스 개발중입니다.</h1>
      <h1>빠른 시일 내에 서비스 제공하도록 하겠습니다.</h1>
      <h1>죄송합니다.<h1>
      <h1>문의가 있으면 dracob11290@gmail.com 으로 문의주세요.<h1>
     </div>
<!-- END MAIN -->
</div>
<script>
// Get the Sidebar
var mySidebar = document.getElementById("mySidebar");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidebar, and add overlay effect
function w3_open() {
  if (mySidebar.style.display === 'block') {
    mySidebar.style.display = 'none';
    overlayBg.style.display = "none";
  } else {
    mySidebar.style.display = 'block';
    overlayBg.style.display = "block";
  }
}

// Close the sidebar with the close button
function w3_close() {
  mySidebar.style.display = "none";
  overlayBg.style.display = "none";
}
</script>

</body>
</html>

site3/templates/pybo/main_page.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% load static %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>

<body>
    <div id="wrap">
        
        {% if error == 'True' %}
        <script>
            alert('예약 실패');
        </script>
        {% endif %}
        {% if error == 'False' %}
        <script>
            alert('예약 예약 성공')
        </script>
        {% endif %}

        <!-- 본문 영역 시작 -->
        <div id="container">
            <div id="vimg">
                <img src="{% static 'logo-png.png' %}" alt="세계지도">
            </div>
            </br>
            </br>
            </br>
            <div id="select" class="">
                <select aria-label="selectP" name="parkinfo" class="form-select form-select-lg" id="selectBox" onchange="ChangeValue()">
                    <option value="0" disabled selected sytle="display:none;">대륙을 선택하세요.</option>
                    <option value="1">남미</option>
                    <option value="2">북미</option>
                    <option value="3">아시아</option>
                    <option value="4">아프리카</option>
                    <option value="5">오세아니아</option>
                    <option value="6">유럽</option>
                </select>
            </div>
            <script>
                window.onload = function ChangeValue(){
                    $(document).ready(function() {
                        $('#selectBox').change(function() {
                            var result = $(' #selectBox option:selected').val();
                            if (result == "1") {
                                $('#table0').hide();
                                $('#table1').show();
                                $('#table2').hide();
                                $('#table3').hide();
                                $('#table4').hide();
                                $('#table5').hide();
                                $('#table6').hide();
                            }
                            else if (result == "2")
                            {
                                $('#table0').hide();
                                $('#table1').hide();
                                $('#table2').show();
                                $('#table3').hide();
                                $('#table4').hide();
                                $('#table5').hide();
                                $('#table6').hide();
                            } 
                            else if (result == "3")
                            {
                                $('#table0').hide();
                                $('#table1').hide();
                                $('#table2').hide();
                                $('#table3').show();
                                $('#table4').hide();
                                $('#table5').hide();
                                $('#table6').hide();
                            } 
                            else if (result == "4")
                            {
                                $('#table0').hide();
                                $('#table1').hide();
                                $('#table2').hide();
                                $('#table3').hide();
                                $('#table4').show();
                                $('#table5').hide();
                                $('#table6').hide();
                            } 
                            else if (result == "5")
                            {
                                $('#table0').hide();
                                $('#table1').hide();
                                $('#table2').hide();
                                $('#table3').hide();
                                $('#table4').hide();
                                $('#table5').show();
                                $('#table6').hide();
                            } 
                            else if (result == "6")
                            {
                                $('#table0').hide();
                                $('#table1').hide();
                                $('#table2').hide();
                                $('#table3').hide();
                                $('#table4').hide();
                                $('#table5').hide();
                                $('#table6').show();
                            } 
                            else {
                                $('#table0').show();
                                $('#table1').hide();
                                $('#table2').hide();
                                $('#table3').hide();
                                $('#table4').hide();
                                $('#table5').hide();
                                $('#table6').hide();
                            }
                            $("#selecBox").submit()
                        }); 
                        }); 
                }
            </script>
            <div id="lot" class="">
                <div id='table0' class="clr">
                    <img src="{% static 'panorama.jpg' %}" alt="panorama">
                </div>
                    <div id='table1' style="display: none;" class="line line1 clr">
                        {% for world in worlds.all %}
                        {% if world.CONTINENT == '1' %}
                        <form method="GET" action = "{% url 'pybo:detail' world.id %}" style="display: inline">
                        <button type="submit">{{ world.COUNTRY }}</button>
                        </form>
                        {% endif %}
                        {% endfor %}
                    </div>
                    <div id='table2' style="display: none;" class="line line1 clr">
                        {% for world in worlds.all %}
                        {% if world.CONTINENT == '2' %}
                        <form method="GET" action = "{% url 'pybo:detail' world.id %}" style="display: inline">
                        <button type="submit">{{ world.COUNTRY }}</button>
                        </form>
                        {% endif %}
                        {% endfor %}
                    </div>
                    <div id='table3' style="display: none;" class="line line1 clr">
                        {% for world in worlds.all %}
                        {% if world.CONTINENT == '3' %}
                        <form method="GET" action = "{% url 'pybo:detail' world.id %}" style="display: inline">
                        <button type="submit">{{ world.COUNTRY }}</button>
                        </form>
                        {% endif %}
                        {% endfor %}
                    </div>
                    <div id='table4' style="display: none;" class="line line1 clr">
                        {% for world in worlds.all %}
                        {% if world.CONTINENT == '4' %}
                        <form method="GET" action = "{% url 'pybo:detail' world.id %}" style="display: inline">
                        <button type="submit">{{ world.COUNTRY }}</button>
                        </form>
                        {% endif %}
                        {% endfor %}
                    </div>
                    <div id='table5' style="display: none;" class="line line1 clr">
                        {% for world in worlds.all %}
                        {% if world.CONTINENT == '5' %}
                        <form method="GET" action = "{% url 'pybo:detail' world.id %}" style="display: inline">
                        <button type="submit">{{ world.COUNTRY }}</button>
                        </form>
                        {% endif %}
                        {% endfor %}
                    </div>
                    <div id='table6' style="display: none;" class="line line1 clr">
                        {% for world in worlds.all %}
                        {% if world.CONTINENT == '6' %}
                        <form method="GET" action = "{% url 'pybo:detail' world.id %}" style="display: inline">
                        <button type="submit">{{ world.COUNTRY }}</button>
                        </form>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div> 
        </div>
    </div>
</body>
</html>
{% endblock %}

site3/templates/pybo/question_detail.html
{% extends 'FAQ.html' %}
{% block content %}
<div class="container my-3">
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

site3/templates/pybo/question_form.html
{% extends 'FAQ.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post">
        {% csrf_token %}
       <!-- 오류표시 Start -->
       {% if form.errors %}
       <div class="alert alert-danger" role="alert">
           {% for field in form %}
           {% if field.errors %}
           <div>
               <strong>{{ field.label }}</strong>
               {{ field.errors }}
           </div>
           {% endif %}
           {% endfor %}
       </div>
       {% endif %}
       <!-- 오류표시 End -->        
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

site3/templates/pybo/question_list.html
{% extends 'FAQ.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'pybo:detail1' question.id %}">{{ question.subject }}</a>
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}